version: '3.3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASS: /run/secrets/mongo_root_password
    secrets:
      - mongo_root_password

  rest:
    build:
      dockerfile: ./Dockerfile
      context: ./app
    ports:
      - 8080:8080
    environment:
      MONGO_USER: root
      MONGO_PASS: /run/secrets/mongo_root_password
      MODE: prod
    secrets:
      - mongo_root_password

  web:
    build:
      dockerfile: ./Dockerfile
      context: ./web
    ports:
      - 80:80

secrets:
  mongo_root_password:
    file: mongo_root_password.txt
